
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: 'DING, Guodong'
#tagline: Full Stack Developer
pic: nate.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
transcript : 'Transcript_DING_Guodong.pdf'
#sidebar links
email: gd.ding.cs@gmail.com
phone: 852 5443 9020
#website: blog.webjeda.com #do not add http://
linkedin: gdding
github: gddingcs
#twitter: '@twittername'

